/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ApiApplicationRouteImport } from './routes/api/application'
import { Route as ApiCoverLetterRouteImport } from './routes/api/cover-letter'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ApiIngestRouteImport } from './routes/api/ingest'
import { Route as ApiLibraryRouteImport } from './routes/api/library'
import { Route as ApiProcessingRouteImport } from './routes/api/processing'
import { Route as ApiRenderRouteImport } from './routes/api/render'
import { Route as ApiRenderLetterRouteImport } from './routes/api/render-letter'
import { Route as ApiResumeRouteImport } from './routes/api/resume'
import { Route as ApiRewriteRouteImport } from './routes/api/rewrite'
import { Route as ApiShareRouteImport } from './routes/api/share'
import { Route as ApiSharedRouteImport } from './routes/api/shared'
import { Route as ApiTargetRouteImport } from './routes/api/target'
import { Route as STokenRouteImport } from './routes/s.$token'
import { Route as ApiAccountDeleteRouteImport } from './routes/api/account/delete'
import { Route as ApiAccountExportRouteImport } from './routes/api/account/export'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiApplicationRoute = ApiApplicationRouteImport.update({
  id: '/api/application',
  path: '/api/application',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCoverLetterRoute = ApiCoverLetterRouteImport.update({
  id: '/api/cover-letter',
  path: '/api/cover-letter',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiIngestRoute = ApiIngestRouteImport.update({
  id: '/api/ingest',
  path: '/api/ingest',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLibraryRoute = ApiLibraryRouteImport.update({
  id: '/api/library',
  path: '/api/library',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProcessingRoute = ApiProcessingRouteImport.update({
  id: '/api/processing',
  path: '/api/processing',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRenderRoute = ApiRenderRouteImport.update({
  id: '/api/render',
  path: '/api/render',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRenderLetterRoute = ApiRenderLetterRouteImport.update({
  id: '/api/render-letter',
  path: '/api/render-letter',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiResumeRoute = ApiResumeRouteImport.update({
  id: '/api/resume',
  path: '/api/resume',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRewriteRoute = ApiRewriteRouteImport.update({
  id: '/api/rewrite',
  path: '/api/rewrite',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiShareRoute = ApiShareRouteImport.update({
  id: '/api/share',
  path: '/api/share',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSharedRoute = ApiSharedRouteImport.update({
  id: '/api/shared',
  path: '/api/shared',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTargetRoute = ApiTargetRouteImport.update({
  id: '/api/target',
  path: '/api/target',
  getParentRoute: () => rootRouteImport,
} as any)
const STokenRoute = STokenRouteImport.update({
  id: '/s/$token',
  path: '/s/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAccountDeleteRoute = ApiAccountDeleteRouteImport.update({
  id: '/api/account/delete',
  path: '/api/account/delete',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAccountExportRoute = ApiAccountExportRouteImport.update({
  id: '/api/account/export',
  path: '/api/account/export',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/privacy': typeof PrivacyRoute
  '/api/application': typeof ApiApplicationRoute
  '/api/cover-letter': typeof ApiCoverLetterRoute
  '/api/health': typeof ApiHealthRoute
  '/api/ingest': typeof ApiIngestRoute
  '/api/library': typeof ApiLibraryRoute
  '/api/processing': typeof ApiProcessingRoute
  '/api/render': typeof ApiRenderRoute
  '/api/render-letter': typeof ApiRenderLetterRoute
  '/api/resume': typeof ApiResumeRoute
  '/api/rewrite': typeof ApiRewriteRoute
  '/api/share': typeof ApiShareRoute
  '/api/shared': typeof ApiSharedRoute
  '/api/target': typeof ApiTargetRoute
  '/s/$token': typeof STokenRoute
  '/api/account/delete': typeof ApiAccountDeleteRoute
  '/api/account/export': typeof ApiAccountExportRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/privacy': typeof PrivacyRoute
  '/api/application': typeof ApiApplicationRoute
  '/api/cover-letter': typeof ApiCoverLetterRoute
  '/api/health': typeof ApiHealthRoute
  '/api/ingest': typeof ApiIngestRoute
  '/api/library': typeof ApiLibraryRoute
  '/api/processing': typeof ApiProcessingRoute
  '/api/render': typeof ApiRenderRoute
  '/api/render-letter': typeof ApiRenderLetterRoute
  '/api/resume': typeof ApiResumeRoute
  '/api/rewrite': typeof ApiRewriteRoute
  '/api/share': typeof ApiShareRoute
  '/api/shared': typeof ApiSharedRoute
  '/api/target': typeof ApiTargetRoute
  '/s/$token': typeof STokenRoute
  '/api/account/delete': typeof ApiAccountDeleteRoute
  '/api/account/export': typeof ApiAccountExportRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/privacy': typeof PrivacyRoute
  '/api/application': typeof ApiApplicationRoute
  '/api/cover-letter': typeof ApiCoverLetterRoute
  '/api/health': typeof ApiHealthRoute
  '/api/ingest': typeof ApiIngestRoute
  '/api/library': typeof ApiLibraryRoute
  '/api/processing': typeof ApiProcessingRoute
  '/api/render': typeof ApiRenderRoute
  '/api/render-letter': typeof ApiRenderLetterRoute
  '/api/resume': typeof ApiResumeRoute
  '/api/rewrite': typeof ApiRewriteRoute
  '/api/share': typeof ApiShareRoute
  '/api/shared': typeof ApiSharedRoute
  '/api/target': typeof ApiTargetRoute
  '/s/$token': typeof STokenRoute
  '/api/account/delete': typeof ApiAccountDeleteRoute
  '/api/account/export': typeof ApiAccountExportRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/privacy'
    | '/api/application'
    | '/api/cover-letter'
    | '/api/health'
    | '/api/ingest'
    | '/api/library'
    | '/api/processing'
    | '/api/render'
    | '/api/render-letter'
    | '/api/resume'
    | '/api/rewrite'
    | '/api/share'
    | '/api/shared'
    | '/api/target'
    | '/s/$token'
    | '/api/account/delete'
    | '/api/account/export'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/privacy'
    | '/api/application'
    | '/api/cover-letter'
    | '/api/health'
    | '/api/ingest'
    | '/api/library'
    | '/api/processing'
    | '/api/render'
    | '/api/render-letter'
    | '/api/resume'
    | '/api/rewrite'
    | '/api/share'
    | '/api/shared'
    | '/api/target'
    | '/s/$token'
    | '/api/account/delete'
    | '/api/account/export'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/privacy'
    | '/api/application'
    | '/api/cover-letter'
    | '/api/health'
    | '/api/ingest'
    | '/api/library'
    | '/api/processing'
    | '/api/render'
    | '/api/render-letter'
    | '/api/resume'
    | '/api/rewrite'
    | '/api/share'
    | '/api/shared'
    | '/api/target'
    | '/s/$token'
    | '/api/account/delete'
    | '/api/account/export'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PrivacyRoute: typeof PrivacyRoute
  ApiApplicationRoute: typeof ApiApplicationRoute
  ApiCoverLetterRoute: typeof ApiCoverLetterRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiIngestRoute: typeof ApiIngestRoute
  ApiLibraryRoute: typeof ApiLibraryRoute
  ApiProcessingRoute: typeof ApiProcessingRoute
  ApiRenderRoute: typeof ApiRenderRoute
  ApiRenderLetterRoute: typeof ApiRenderLetterRoute
  ApiResumeRoute: typeof ApiResumeRoute
  ApiRewriteRoute: typeof ApiRewriteRoute
  ApiShareRoute: typeof ApiShareRoute
  ApiSharedRoute: typeof ApiSharedRoute
  ApiTargetRoute: typeof ApiTargetRoute
  STokenRoute: typeof STokenRoute
  ApiAccountDeleteRoute: typeof ApiAccountDeleteRoute
  ApiAccountExportRoute: typeof ApiAccountExportRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/application': {
      id: '/api/application'
      path: '/api/application'
      fullPath: '/api/application'
      preLoaderRoute: typeof ApiApplicationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cover-letter': {
      id: '/api/cover-letter'
      path: '/api/cover-letter'
      fullPath: '/api/cover-letter'
      preLoaderRoute: typeof ApiCoverLetterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ingest': {
      id: '/api/ingest'
      path: '/api/ingest'
      fullPath: '/api/ingest'
      preLoaderRoute: typeof ApiIngestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/library': {
      id: '/api/library'
      path: '/api/library'
      fullPath: '/api/library'
      preLoaderRoute: typeof ApiLibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/processing': {
      id: '/api/processing'
      path: '/api/processing'
      fullPath: '/api/processing'
      preLoaderRoute: typeof ApiProcessingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/render': {
      id: '/api/render'
      path: '/api/render'
      fullPath: '/api/render'
      preLoaderRoute: typeof ApiRenderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/render-letter': {
      id: '/api/render-letter'
      path: '/api/render-letter'
      fullPath: '/api/render-letter'
      preLoaderRoute: typeof ApiRenderLetterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/resume': {
      id: '/api/resume'
      path: '/api/resume'
      fullPath: '/api/resume'
      preLoaderRoute: typeof ApiResumeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/rewrite': {
      id: '/api/rewrite'
      path: '/api/rewrite'
      fullPath: '/api/rewrite'
      preLoaderRoute: typeof ApiRewriteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/share': {
      id: '/api/share'
      path: '/api/share'
      fullPath: '/api/share'
      preLoaderRoute: typeof ApiShareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/shared': {
      id: '/api/shared'
      path: '/api/shared'
      fullPath: '/api/shared'
      preLoaderRoute: typeof ApiSharedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/target': {
      id: '/api/target'
      path: '/api/target'
      fullPath: '/api/target'
      preLoaderRoute: typeof ApiTargetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s/$token': {
      id: '/s/$token'
      path: '/s/$token'
      fullPath: '/s/$token'
      preLoaderRoute: typeof STokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/account/delete': {
      id: '/api/account/delete'
      path: '/api/account/delete'
      fullPath: '/api/account/delete'
      preLoaderRoute: typeof ApiAccountDeleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/account/export': {
      id: '/api/account/export'
      path: '/api/account/export'
      fullPath: '/api/account/export'
      preLoaderRoute: typeof ApiAccountExportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PrivacyRoute: PrivacyRoute,
  ApiApplicationRoute: ApiApplicationRoute,
  ApiCoverLetterRoute: ApiCoverLetterRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiIngestRoute: ApiIngestRoute,
  ApiLibraryRoute: ApiLibraryRoute,
  ApiProcessingRoute: ApiProcessingRoute,
  ApiRenderRoute: ApiRenderRoute,
  ApiRenderLetterRoute: ApiRenderLetterRoute,
  ApiResumeRoute: ApiResumeRoute,
  ApiRewriteRoute: ApiRewriteRoute,
  ApiShareRoute: ApiShareRoute,
  ApiSharedRoute: ApiSharedRoute,
  ApiTargetRoute: ApiTargetRoute,
  STokenRoute: STokenRoute,
  ApiAccountDeleteRoute: ApiAccountDeleteRoute,
  ApiAccountExportRoute: ApiAccountExportRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
