/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ApiIngestRouteImport } from './routes/api/ingest'
import { Route as ApiProcessingRouteImport } from './routes/api/processing'
import { Route as ApiRenderRouteImport } from './routes/api/render'
import { Route as ApiResumeRouteImport } from './routes/api/resume'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiIngestRoute = ApiIngestRouteImport.update({
  id: '/api/ingest',
  path: '/api/ingest',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProcessingRoute = ApiProcessingRouteImport.update({
  id: '/api/processing',
  path: '/api/processing',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRenderRoute = ApiRenderRouteImport.update({
  id: '/api/render',
  path: '/api/render',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiResumeRoute = ApiResumeRouteImport.update({
  id: '/api/resume',
  path: '/api/resume',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/privacy': typeof PrivacyRoute
  '/api/health': typeof ApiHealthRoute
  '/api/ingest': typeof ApiIngestRoute
  '/api/processing': typeof ApiProcessingRoute
  '/api/render': typeof ApiRenderRoute
  '/api/resume': typeof ApiResumeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/privacy': typeof PrivacyRoute
  '/api/health': typeof ApiHealthRoute
  '/api/ingest': typeof ApiIngestRoute
  '/api/processing': typeof ApiProcessingRoute
  '/api/render': typeof ApiRenderRoute
  '/api/resume': typeof ApiResumeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/privacy': typeof PrivacyRoute
  '/api/health': typeof ApiHealthRoute
  '/api/ingest': typeof ApiIngestRoute
  '/api/processing': typeof ApiProcessingRoute
  '/api/render': typeof ApiRenderRoute
  '/api/resume': typeof ApiResumeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/privacy'
    | '/api/health'
    | '/api/ingest'
    | '/api/processing'
    | '/api/render'
    | '/api/resume'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/privacy'
    | '/api/health'
    | '/api/ingest'
    | '/api/processing'
    | '/api/render'
    | '/api/resume'
  id:
    | '__root__'
    | '/'
    | '/privacy'
    | '/api/health'
    | '/api/ingest'
    | '/api/processing'
    | '/api/render'
    | '/api/resume'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PrivacyRoute: typeof PrivacyRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiIngestRoute: typeof ApiIngestRoute
  ApiProcessingRoute: typeof ApiProcessingRoute
  ApiRenderRoute: typeof ApiRenderRoute
  ApiResumeRoute: typeof ApiResumeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ingest': {
      id: '/api/ingest'
      path: '/api/ingest'
      fullPath: '/api/ingest'
      preLoaderRoute: typeof ApiIngestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/processing': {
      id: '/api/processing'
      path: '/api/processing'
      fullPath: '/api/processing'
      preLoaderRoute: typeof ApiProcessingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/render': {
      id: '/api/render'
      path: '/api/render'
      fullPath: '/api/render'
      preLoaderRoute: typeof ApiRenderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/resume': {
      id: '/api/resume'
      path: '/api/resume'
      fullPath: '/api/resume'
      preLoaderRoute: typeof ApiResumeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PrivacyRoute: PrivacyRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiIngestRoute: ApiIngestRoute,
  ApiProcessingRoute: ApiProcessingRoute,
  ApiRenderRoute: ApiRenderRoute,
  ApiResumeRoute: ApiResumeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
